apiVersion: v1
kind: ReplicationController
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    app: customer
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
      - name: customer-container
        image: al3xzx/customer
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
