apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: ecom.info
      http:
        paths:
        - path: /p
          pathType: Prefix
          backend:
            serviceName: product-service
            servicePort: 8091