apiVersion: v1
kind: Ingress
metadata:
    name: api-gateway
spec:
    rules:
        - host: "test.apiGateway.com"
          http:
            paths:
                - path: "/customer_service"
                  pathType: Prefix
                  backend:
                    serviceName: customer-service
                    servicePort: 8090
                - path: "/product_service"
                  pathType: Prefix
                    backend:
                      serviceName: product-service
                      servicePort: 8091
                - path: "/order_service"
                  pathType: Prefix
                    backend:
                      serviceName: order-service
                      servicePort: 8092