#order
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 8092
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: order
spec:
  replicas: 1
  selector:
    app: order
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        image: al3xzx/order:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8092
